---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - SonarrConfig:/config
      - TV:/nfs/media/TV
      - Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
volumes:
  SonarrConfig:
    external: true
  TV:
    external: true
  Downloads:
    external: true
