---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - RadarrConfig:/config
      - Movies:/nfs/media/Movies
      - Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
volumes:
  RadarrConfig:
    external: true
  Movies:
    external: true
  Downloads:
    external: true

